apiVersion: v1
kind: Service
metadata:
  name: dn-1-slaves-hvl-bigdata-hadoop-331-master-standby
  namespace: hvl
  labels:
    component: 1-slaves-hvl-bigdata-hadoop-331-master-standby
spec:
  ports:
  - port: 22
    name: ssh
    protocol: TCP
  selector:
    component: 1-slaves-hvl-bigdata-hadoop-331-master-standby
