kind: Deployment
apiVersion: apps/v1
metadata:
  name: 1-slaves-hvl-bigdata-hadoop-331-master-standby
  namespace: hvl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: 1-slaves-hvl-bigdata-hadoop-331-master-standby
  template:
    metadata:
      labels:
        component: 1-slaves-hvl-bigdata-hadoop-331-master-standby
    spec:
      #imagePullSecrets:
      #  - name: docker-registry-key
      hostname: 1-slaves-hvl-bigdata-hadoop-331-master-standby
      containers:
        - name: 1-slaves-hvl-bigdata-hadoop-331-master-standby
          image: ensaradaletai/hadoop-img-3.3.1
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["echo 'Inıt script starting' && /tmp/init-cluster-config.sh e58c5ecbdc 1 1-slaves-hvl-bigdata-hadoop-331 0 && /tmp/start-master-standby-hadoop.sh 0"]
          ports:
            - containerPort: 50071
            - containerPort: 9689
            - containerPort: 22
          resources:
            requests:
              cpu: 1
              memory: 2048Mi
---
kind: Service
apiVersion: v1
metadata:
  name: hvl-bigdata-1-slaves-331-svc-standby
  namespace: hvl
spec:
  type: NodePort
  ports:
    - name: standbynodeadmin
      port: 50071
      nodePort: 31000
      protocol: TCP
    - name: standbynoderesourcemanager
      port: 9689
      nodePort: 31100
      protocol: TCP
  selector:
     component: 1-slaves-hvl-bigdata-hadoop-331-master-standby
