apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: hvl
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: 1-slaves-hvl-bigdata-hadoop-331-metadb-srv
  namespace: hvl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: 1-slaves-hvl-bigdata-hadoop-331-metadb-srv
  template:
    metadata:
      labels:
        component: 1-slaves-hvl-bigdata-hadoop-331-metadb-srv
    spec:
      #imagePullSecrets:
      #  - name: docker-registry-key
      hostname: 1-slaves-hvl-bigdata-hadoop-331-metadb-srv
      containers:
        - name: 1-slaves-hvl-bigdata-hadoop-331-metadb-srv
          image: ensaradaletai/bigdata_postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: POSTGRES_PASSWORD
              value: "e58c5ecbdc"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            #- name: 1-slaves-hvl-bigdata-331-metadb-config
            #  mountPath: /etc/mysql/conf.d/
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-storage
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
      - name: postgres-pv-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: dn-1-slaves-hvl-bigdata-hadoop-331-metadb-srv
  namespace: hvl
  labels:
    component: 1-slaves-hvl-bigdata-hadoop-331-metadb-srv
spec:
  type: NodePort
  ports:
  - port:  5432
    name: cluster-metadb
    protocol: TCP
  selector:
    component: 1-slaves-hvl-bigdata-hadoop-331-metadb-srv
